### ISSUE TITLE
IntPic 0.2.3 tests fail with GAP stable-4.10 and master

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/intpic#6] opened 2019-04-22 22:01 UTC
https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10/jobs/523030730 and https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/522630996 report diffs, for example
```
============================OUTPUT START==============================
#I  RunPackageTests("intpic", "0.2.3", "tst/testall.tst", "auto");
 ┌───────┐   GAP 4.dev of today
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv3
 Configuration:  gmp 6.1.2, readline
 Loaded workspace: wsp.g
 Packages:   AClib 1.3.1, Alnuth 3.1.0, AtlasRep 1.5.1, AutoDoc 2019.02.22, 
             AutPGrp 1.10, Browse 1.8.8, Carat 2.2.3, CRISP 1.4.4, 
             Cryst 4.1.18, CrystCat 1.1.8, CTblLib 1.2.2, FactInt 1.6.2, 
             FGA 1.4.0, GAPDoc 1.6.2, IntPic 0.2.3, IO 4.6.0, IRREDSOL 1.4, 
             LAGUNA 3.9.2, NumericalSgps 1.1.11, Polenta 1.3.8, 
             Polycyclic 2.14, PrimGrp 3.3.2, RadiRoot 2.8, ResClasses 4.7.2, 
             SmallGrp 1.3, Sophus 1.24, SpinSym 1.5.1, TomLib 1.2.7, 
             TransGrp 2.0.4, utils 0.61
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
########> Diff in /home/gap/inst/gap-stable-4.10/pkg/IntPic-0.2.3/tst/testall.\
tst:661
# Input is:
SetOfNumericalSemigroups(rec(set:=rec(genus:=6),filter:=rec(type:= 2),
order:="multiplicity"));
# Expected output:
[ <Numerical semigroup with 3 generators>, 
  <Numerical semigroup with 3 generators>, 
  <Numerical semigroup with 4 generators>, 
  <Numerical semigroup with 5 generators>, 
  <Numerical semigroup with 5 generators>, 
  <Numerical semigroup with 6 generators> ]
# But found:
[ <Numerical semigroup with 3 generators>, 
  <Numerical semigroup with 3 generators>, 
  <Numerical semigroup with 3 generators>, 
  <Numerical semigroup with 3 generators>, 
  <Numerical semigroup with 3 generators>, 
  <Numerical semigroup with 5 generators> ]
########
########> Diff in /home/gap/inst/gap-stable-4.10/pkg/IntPic-0.2.3/tst/testall.\
tst:669
# Input is:
SetOfNumericalSemigroups(rec(set:=rec(genus:=6),filter:=rec(type:= 2), order:=\
"frobenius"));                                                 
# Expected output:
[ <Numerical semigroup with 3 generators>, 
  <Numerical semigroup with 5 generators>, 
  <Numerical semigroup with 5 generators>, 
  <Numerical semigroup with 3 generators>, 
  <Numerical semigroup with 4 generators>, 
  <Numerical semigroup with 6 generators> ]
# But found:
[ <Numerical semigroup with 3 generators>, 
  <Numerical semigroup with 3 generators>, 
  <Numerical semigroup with 3 generators>, 
  <Numerical semigroup with 3 generators>, 
  <Numerical semigroup with 3 generators>, 
  <Numerical semigroup with 5 generators> ]
########
IntPic package: testall.tst
msecs: 60
#I  Errors detected while testing package intpic 0.2.3
#I  using the test file `tst/testall.tst'
#I  RunPackageTests("intpic", "0.2.3", "tst/testall.tst", "auto"): runtime 376
============================OUTPUT END================================
```
I will have to move IntPic to "staging" versions of package tests until this is resolved.

**Comment by ManuelAFDelgado** [comment] 2021-04-01 06:01
Caused by a change in the numericalsgps package. Fixed in Version 0.2.4 (23/08/2019).

**Closed as completed by ManuelAFDelgado** 2021-04-01 06:01 UTC
